import 'package:flutter/material.dart';

class TermsConditionsPage extends StatelessWidget {
  const TermsConditionsPage({super.key});

  @override
  Widget build(BuildContext context) {
    final isDesktop = MediaQuery.of(context).size.width > 768;

    return Scaffold(
      backgroundColor: const Color(0xFFF8FAFC),
      appBar: PreferredSize(
        preferredSize: Size.fromHeight(isDesktop ? 90 : 80),
        child: Container(
          decoration: BoxDecoration(
            color: Colors.white,
            boxShadow: [
              BoxShadow(
                color: Colors.black.withOpacity(0.08),
                blurRadius: 20,
                offset: const Offset(0, 4),
                spreadRadius: 0,
              ),
            ],
          ),
          child: SafeArea(
            child: Padding(
              padding: EdgeInsets.symmetric(
                horizontal: isDesktop ? 32.0 : 20.0,
                vertical: isDesktop ? 24.0 : 20.0,
              ),
              child: Row(
                children: [
                  GestureDetector(
                    onTap: () => Navigator.pop(context),
                    child: Container(
                      padding: const EdgeInsets.all(8),
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(12),
                        color: Colors.white,
                      ),
                      child: Image.asset(
                        "assets/images/logo1.png",
                        height: isDesktop ? 50 : 45,
                        fit: BoxFit.contain,
                      ),
                    ),
                  ),
                  const SizedBox(width: 20),
                  Text(
                    "Terms and Conditions",
                    style: TextStyle(
                      fontSize: isDesktop ? 24 : 20,
                      fontWeight: FontWeight.w700,
                      color: const Color(0xFF1E293B),
                      letterSpacing: -0.5,
                    ),
                  ),
                  const Spacer(),
                  Container(
                    decoration: BoxDecoration(
                      color: const Color(0xFF3B82F6).withOpacity(0.1),
                      borderRadius: BorderRadius.circular(12),
                    ),
                    child: IconButton(
                      icon: Icon(
                        Icons.arrow_back_rounded,
                        color: const Color(0xFF3B82F6),
                        size: isDesktop ? 24 : 20,
                      ),
                      onPressed: () => Navigator.pop(context),
                    ),
                  ),
                ],
              ),
            ),
          ),
        ),
      ),
      body: SingleChildScrollView(
        padding: EdgeInsets.symmetric(
          horizontal: isDesktop ? 48.0 : 24.0,
          vertical: isDesktop ? 48.0 : 32.0,
        ),
        child: Center(
          child: ConstrainedBox(
            constraints: BoxConstraints(
              maxWidth: isDesktop ? 900 : double.infinity,
            ),
            child: Container(
              padding: EdgeInsets.all(isDesktop ? 48 : 32),
              decoration: BoxDecoration(
                gradient: LinearGradient(
                  begin: Alignment.topLeft,
                  end: Alignment.bottomRight,
                  colors: [Colors.white, Colors.grey.shade50],
                ),
                borderRadius: BorderRadius.circular(24),
                boxShadow: [
                  BoxShadow(
                    color: Colors.black.withOpacity(0.08),
                    blurRadius: 30,
                    offset: const Offset(0, 8),
                    spreadRadius: 0,
                  ),
                  BoxShadow(
                    color: Colors.black.withOpacity(0.04),
                    blurRadius: 60,
                    offset: const Offset(0, 16),
                    spreadRadius: 0,
                  ),
                ],
                border: Border.all(color: Colors.grey.shade100, width: 1),
              ),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  _buildIntroduction(isDesktop),
                  const SizedBox(height: 32),
                  _buildSection("1. Information-Only Disclaimer", [
                    "ROSS AI provides information, document templates, and research support tools.",
                    "We do not provide legal advice. Any information generated by ROSS AI shall not be treated as a substitute for professional legal consultation.",
                    "You are solely responsible for seeking independent legal counsel for your specific circumstances.",
                  ], isDesktop),
                  const SizedBox(height: 24),
                  _buildSection("2. Use of Services", [
                    "You may use ROSS AI for lawful purposes only.",
                    "You agree not to misuse or exploit the platform for fraudulent, harmful, or illegal activities.",
                  ], isDesktop),
                  const SizedBox(height: 24),
                  _buildSection("3. Data Collection & Privacy", [
                    "ROSS AI may collect personal data such as name, email, and account details for account creation and platform functionality.",
                    "We may also collect usage data (search queries, uploads, interactions) to improve services.",
                    "Cookies are used to enhance user experience, track preferences, and improve performance. By using the platform, you consent to cookie usage.",
                  ], isDesktop),
                  const SizedBox(height: 24),
                  _buildSection("4. Data Storage and Security", [
                    "Uploaded documents, including text and images, may be temporarily stored to enable features such as Timeline Extraction and Precedent Finder.",
                    "We take reasonable steps to protect your data; however, we cannot guarantee absolute security.",
                    "You are responsible for safeguarding your account credentials.",
                  ], isDesktop),
                  const SizedBox(height: 24),
                  _buildSection("5. Intellectual Property", [
                    "All templates, features, and tools provided by ROSS AI are the intellectual property of the developers.",
                    "Users retain ownership of any documents or materials they upload.",
                  ], isDesktop),
                  const SizedBox(height: 24),
                  _buildSection("6. Limitation of Liability", [
                    "ROSS AI and its developers shall not be held responsible for any errors, omissions, or inaccuracies in the information provided.",
                    "We are not liable for any damages, losses, or consequences arising from the use or misuse of ROSS AI.",
                  ], isDesktop),
                  const SizedBox(height: 24),
                  _buildSection("7. Modifications to Service", [
                    "We may update or change features, content, or these Terms at any time.",
                    "Continued use of the platform after updates implies acceptance of the revised terms.",
                  ], isDesktop),
                  const SizedBox(height: 24),
                  _buildSection("8. Governing Law", [
                    "These Terms shall be governed by and construed in accordance with the laws of courts of India.",
                  ], isDesktop),
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }

  Widget _buildIntroduction(bool isDesktop) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          "Terms and Conditions",
          style: TextStyle(
            fontSize: isDesktop ? 32 : 28,
            fontWeight: FontWeight.w800,
            color: const Color(0xFF1E293B),
            letterSpacing: -0.5,
          ),
        ),
        const SizedBox(height: 12),
        Text(
          "Welcome to ROSS AI. By accessing or using this platform, you agree to the following terms and conditions. Please read them carefully.",
          style: TextStyle(
            fontSize: isDesktop ? 18 : 16,
            color: const Color(0xFF64748B),
            fontWeight: FontWeight.w500,
            height: 1.6,
          ),
        ),
      ],
    );
  }

  Widget _buildSection(String title, List<String> points, bool isDesktop) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          title,
          style: TextStyle(
            fontSize: isDesktop ? 22 : 20,
            fontWeight: FontWeight.w700,
            color: const Color(0xFF1E293B),
            letterSpacing: -0.3,
          ),
        ),
        const SizedBox(height: 12),
        ...points.map(
          (point) => Padding(
            padding: const EdgeInsets.only(bottom: 8.0),
            child: Row(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Container(
                  margin: const EdgeInsets.only(top: 6, right: 12),
                  width: 6,
                  height: 6,
                  decoration: BoxDecoration(
                    color: const Color(0xFF3B82F6),
                    shape: BoxShape.circle,
                  ),
                ),
                Expanded(
                  child: Text(
                    point,
                    style: TextStyle(
                      fontSize: isDesktop ? 16 : 15,
                      color: const Color(0xFF475569),
                      height: 1.6,
                    ),
                  ),
                ),
              ],
            ),
          ),
        ),
      ],
    );
  }
}
