// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOfNKl9Qj7GnNPTsqZTbDmezXoL_B525M',
    appId: '1:1042853929889:web:6cf749af10e513cb9121e0',
    messagingSenderId: '1042853929889',
    projectId: 'ross-ai-b6809',
    authDomain: 'ross-ai-b6809.firebaseapp.com',
    storageBucket: 'ross-ai-b6809.firebasestorage.app',
    measurementId: 'G-3EK1BL44X2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6czzITpkTpiMnL5qnam0ZLnyPSI3Q7Tk',
    appId: '1:1042853929889:android:9a8e4f7ddb137e899121e0',
    messagingSenderId: '1042853929889',
    projectId: 'ross-ai-b6809',
    storageBucket: 'ross-ai-b6809.firebasestorage.app',
  );
}
